#!/usr/bin/env python3
"""Compute every `sql-live` fence's `height=` and the CSS that matches it.

    python3 fit-sql-slides.py            # report only
    python3 fit-sql-slides.py --write    # rewrite deck.md + the CSS block

WHY THIS IS A SCRIPT AND NOT A TABLE OF HAND-PICKED NUMBERS
------------------------------------------------------------
Week 9 learned this the expensive way (its deck README, "The height budget,
measured rather than guessed"). Three things have to agree or a slide is
silently wrong:

  1. `height=` on the fence — the widget's whole box;
  2. a CSS rule `.deck-sql[style*="<height>px"] { --w10-editor-lines: N }`,
     because the editor textarea carries a hardcoded `rows="8"` and will clip
     a longer query WITHOUT registering as overflow (the textarea scrolls, so
     the slide "fits" while the query is cut off mid-line where a student
     reads it);
  3. room under the widget for the PINNED RESULT, which is not part of the
     widget at all — it renders as a `<table>` sibling BELOW it, 40px of
     header plus ~32.3px per row.

Deriving all three from one place is the only way they stay in step when a
query gains a line.

THE BUDGET, from week 9's measurements on this same platform and stage:

    stage                              720 px
      - top offset (no h1 on a data slide) 40
      - the <pre> wrapper's own padding     44
      - bottom margin                       14
    ------------------------------------------
    available to widget + pinned table   622 px

    pinned table  = 40 + 32.3 * rows
    widget        = editor + 44 (button row) + 24 (padding) + results pane
    editor        = lines * 23.2 + 18

The results pane inside the widget is capped by CSS (150px in week 9); it is
what the presenter sees before pinning. The pinned table below is what the
audience reads.
"""

from __future__ import annotations

import argparse
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
DECK = HERE / "deck.md"
CSS = HERE / "mbua512-week-10.css"

STAGE = 720
TOP_OFFSET = 40
PRE_PADDING = 44
BOTTOM_MARGIN = 14
AVAILABLE = STAGE - TOP_OFFSET - PRE_PADDING - BOTTOM_MARGIN  # 622

LINE_PX = 23.2
EDITOR_PAD = 18
BUTTON_ROW = 44
WIDGET_PAD = 24
RESULTS_PANE = 150          # the in-widget pane, capped in CSS
TIGHT_RESULTS_PANE = 62     # for a one-row answer on a long query (see plan())
TABLE_HEADER = 40
TABLE_ROW = 32.3

PLATFORM_CEILING = 680      # deckWidgets clamps height= to 200..680

MARKER_BEGIN = "/* === WEEK-10 SQL HEIGHTS: GENERATED BY fit-sql-slides.py === */"
MARKER_END = "/* === END WEEK-10 SQL HEIGHTS === */"

FENCE_RE = re.compile(r"(```sql-live)([^\n]*)(\n)(.*?)(```)", re.S)

# How many rows each fence's PINNED result will show. Derived from the query
# where it is knowable (a GROUP BY over a two-valued column returns 2; a
# one-row aggregate returns 1) and from `limit=` where the fence caps a row
# listing. Kept as an explicit table because getting it wrong is exactly the
# failure week 9 hit on its first pin pass: every widget reported its
# requested height while eight slides overran, because the table underneath
# was not in anyone's budget.
PINNED_ROWS = {
    1: 5,    # row listing, limit=5
    2: 2,    # GROUP BY test_group
    3: 2,
    4: 2,
    5: 1,    # one row of counts
    6: 1,
    7: 1,
    8: 1,
    9: 2,    # GROUP BY test_group
    10: 2,   # GROUP BY converted
    11: 2,   # GROUP BY version
    12: 1,
    13: 2,
}


def plan(fences):
    out = []
    for i, (_, info, _, sql, _) in enumerate(fences, start=1):
        lines = len(sql.rstrip("\n").split("\n"))
        editor = lines * LINE_PX + EDITOR_PAD
        want = editor + BUTTON_ROW + WIDGET_PAD + RESULTS_PANE
        rows = PINNED_ROWS.get(i, 2)
        table = TABLE_HEADER + TABLE_ROW * rows
        room = AVAILABLE - table
        # A one-row answer does not need the full 150px in-widget pane: the
        # PINNED table below is what the audience reads, and the pane is only
        # what the presenter sees between Run and Pin. Tightening it on the
        # longest queries buys back exactly the room their editor wants. Week
        # 9 did the same for its 18-line Spearman slide.
        pane = RESULTS_PANE
        if rows == 1 and want > room:
            pane = TIGHT_RESULTS_PANE
            want = editor + BUTTON_ROW + WIDGET_PAD + pane
        # Round UP: int() truncation alone leaves every query a fraction of a
        # pixel short and reports a phantom "editor scrolls" on slides that
        # fit perfectly well.
        height = int(min(-(-want // 1), room, PLATFORM_CEILING))
        # A widget below ~240px cannot show its buttons and a result at all.
        height = max(height, 240)
        clipped = want > height + 0.5
        out.append({
            "n": i, "lines": lines, "editor": editor, "want": want,
            "rows": rows, "table": table, "room": room,
            "height": height, "clipped": clipped, "pane": pane,
            # What the CSS must tell the textarea. If the budget forced the
            # widget smaller than the query wants, the editor still gets the
            # full line count and scrolls INSIDE a pane sized to what is left
            # — better a short scroll than a query cut mid-line.
            "css_lines": lines,
        })
    return out


def css_block(rows) -> str:
    lines = [
        MARKER_BEGIN,
        "/*",
        " * Generated. Do not hand-edit: `fit-sql-slides.py --write` rewrites",
        " * this block and the matching `height=` on every fence together, and",
        " * the two must agree or a query is clipped without registering as",
        " * overflow (the textarea scrolls — see the deck README).",
        " *",
        " * Each rule maps a widget height to the number of editor lines its",
        " * query needs. The heights are distinct by construction so the",
        " * attribute selectors cannot collide.",
        " */",
    ]
    by_height = {}
    for r in rows:
        by_height.setdefault(r["height"], set()).add(r["css_lines"])
    for height in sorted(by_height):
        ls = by_height[height]
        if len(ls) > 1:
            raise SystemExit(
                f"height {height}px is shared by queries of different lengths "
                f"{sorted(ls)} — nudge one fence so the selectors stay distinct")
        n = ls.pop()
        lines.append(
            f'.reveal .slides section .deck-sql[style*="{height}px"] '
            f"{{ --w10-editor-lines: {n}; }}")
    tight = sorted({r["height"] for r in rows
                    if r["pane"] != RESULTS_PANE})
    if tight:
        lines += [
            "",
            "/* The longest queries return a SINGLE row, so their in-widget",
            " * results pane is tightened to make room for the editor. The",
            " * PINNED table below the widget is what the audience reads; this",
            " * pane is only what the presenter sees between Run and Pin. */",
        ]
        for height in tight:
            lines.append(
                f'.reveal .slides section .deck-sql[style*="{height}px"] '
                f".deck-sql-results-pane {{ max-height: {TIGHT_RESULTS_PANE}px; }}")
    lines += [
        "",
        "/* Everything else keeps the roomier pane. */",
        ".reveal .slides section .deck-sql--rows .deck-sql-results-pane {",
        f"  max-height: {RESULTS_PANE}px;",
        "}",
        "",
        "/* The editor's own height, from the line count above. The textarea's",
        " * hardcoded rows=\"8\" is only a default, so this wins. */",
        ".reveal .slides section .deck-sql--rows .deck-sql-editor {",
        "  height: calc(var(--w10-editor-lines, 8) * 23.2px + 18px);",
        "  min-height: 0;",
        "  overflow: auto;",
        "}",
        MARKER_END,
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    md = DECK.read_text()
    fences = FENCE_RE.findall(md)
    rows = plan(fences)

    print(f"{'#':>3} {'lines':>5} {'want':>6} {'rows':>4} {'table':>6} "
          f"{'room':>6} {'height':>6}  note")
    for r in rows:
        note = ""
        if r["clipped"]:
            note = (f"editor scrolls ({r['want'] - r['height']:.0f}px short) "
                    "— LOOK at the screenshot")
        print(f"{r['n']:>3} {r['lines']:>5} {r['want']:>6.0f} {r['rows']:>4} "
              f"{r['table']:>6.0f} {r['room']:>6.0f} {r['height']:>6}  {note}")

    if not args.write:
        print("\n(report only — pass --write to apply)")
        return 0

    # --- rewrite the fences ---
    it = iter(rows)

    def repl(m):
        r = next(it)
        info = m.group(2)
        if "height=" in info:
            info = re.sub(r"height=\d+", f"height={r['height']}", info)
        else:
            info = info.rstrip() + f" height={r['height']}"
        return m.group(1) + info + m.group(3) + m.group(4) + m.group(5)

    DECK.write_text(FENCE_RE.sub(repl, md))
    print(f"\nrewrote {len(rows)} fences in {DECK.name}")

    # --- rewrite the CSS block ---
    css = CSS.read_text()
    block = css_block(rows)
    if MARKER_BEGIN in css:
        start = css.index(MARKER_BEGIN)
        end = css.index(MARKER_END) + len(MARKER_END) + 1
        css = css[:start] + block + css[end:]
    else:
        css = css.rstrip() + "\n\n" + block
    CSS.write_text(css)
    if css.count("/*") != css.count("*/"):
        raise SystemExit(
            f"stylesheet comment imbalance after the rewrite: "
            f"{css.count('/*')} '/*' vs {css.count('*/')} '*/'")
    print(f"rewrote the generated block in {CSS.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
